# Generated by Django 4.0.4 on 2022-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_authorprofile_author_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
