# Generated by Django 4.0.4 on 2022-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_authorprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='http://ssl.gstatic.com/accounts/ui/avatar_2x.png', null=True, upload_to=''),
        ),
    ]
