# Generated by Django 4.0.4 on 2022-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_authorprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='tagline',
            field=models.ImageField(blank=True, default='I am blog user', null=True, upload_to=''),
        ),
    ]
