# Generated by Django 4.0.4 on 2022-06-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0006_post_cover_img_alter_authorprofile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogApp_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
